### PR TITLE
more samples

### PR DESCRIPTION
**Pull request by mickhansen**
@sgryt Please assist in identifying tooltips :)

### CODE REVIEW

**Comment by sgryt** [comment]
@mickhansen Maybe we should add quotes back to the names of complex-valued props ?

image

Will look into adding more explainers asap.

**Comment by mickhansen** [comment]
> @mickhansen Maybe we should add quotes back to the names of complex-valued props ?
> 
> image
> 
> Will look into adding more explainers asap.

Ah yes, an oversight.

**Comment by mickhansen** [comment]
@sgryt Any tokens we are missing we use in docs? Yes, Sofort, etc?

**Comment by mickhansen** [comment]
@sgryt Will merge this and try to implement in docs to see how it looks.

**Pull request merged**
